<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.fuin</groupId>
        <artifactId>pom</artifactId>
        <version>2.0.0</version>
    </parent>

    <groupId>org.fuin.srcgen4j</groupId>
    <artifactId>srcgen4j-core</artifactId>
    <version>0.5.0-SNAPSHOT</version>

    <description>Source code generation for Java (Core)</description>
    <url>http://www.fuin.org/srcgen4j/core/</url>

    <scm>
        <url>https://github.com/fuinorg/srcgen4j-core/</url>
        <connection>scm:git:git://github.com/fuinorg/srcgen4j-core.git</connection>
        <developerConnection>scm:git:git@github.com:fuinorg/srcgen4j-core.git</developerConnection>
    </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/fuinorg/srcgen4j-core/issues</url>
    </issueManagement>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <assertj-core.version>3.26.3</assertj-core.version>
        <checker-qual.version>3.49.5</checker-qual.version>
        <commons-io.version>2.20.0</commons-io.version>
        <error_prone_annotations.version>2.40.0</error_prone_annotations.version>
        <jakarta.validation-api.version>3.0.2</jakarta.validation-api.version>
        <jaxb-runtime.version>4.0.5</jaxb-runtime.version>
        <junit.version>5.9.1</junit.version>
        <logback-classic.version>1.5.18</logback-classic.version>
        <objects4j-core.version>0.11.1-SNAPSHOT</objects4j-core.version>
        <openpojo.version>0.9.1</openpojo.version>
        <org.eclipse.core.runtime.version>3.31.0</org.eclipse.core.runtime.version>
        <org.eclipse.emf.ecore.change.version>2.16.0</org.eclipse.emf.ecore.change.version>
        <org.eclipse.emf.ecore.version>2.36.0</org.eclipse.emf.ecore.version>
        <org.fuin.xsample.dsl.version>0.0.2</org.fuin.xsample.dsl.version>
        <slf4j-api.version>2.0.6</slf4j-api.version>
        <srcgen4j-commons.version>0.5.0-SNAPSHOT</srcgen4j-commons.version>
        <units4j.version>0.12.0</units4j.version>
        <velocity-engine-core.version>2.4.1</velocity-engine-core.version>
        <xtext.version>2.39.0</xtext.version>
    </properties>

    <dependencies>

        <!-- Compile -->

        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-qual</artifactId>
            <version>${checker-qual.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.errorprone</groupId>
            <artifactId>error_prone_annotations</artifactId>
            <version>${error_prone_annotations.version}</version>
        </dependency>

        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>${jakarta.validation-api.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fuin.objects4j</groupId>
            <artifactId>objects4j-core</artifactId>
            <version>${objects4j-core.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fuin.srcgen4j</groupId>
            <artifactId>srcgen4j-commons</artifactId>
            <version>${srcgen4j-commons.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>

        <!-- Technology JARs - Add this dependencies to your POM if you need it -->

        <!-- Velocity -->

        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>${velocity-engine-core.version}</version>
            <optional>true</optional>
        </dependency>

        <!-- EMF Ecore -->

        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore</artifactId>
            <version>${org.eclipse.emf.ecore.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore.change</artifactId>
            <version>${org.eclipse.emf.ecore.change.version}</version>
            <optional>true</optional>
        </dependency>

        <!-- XTEXT -->

        <dependency>
            <groupId>org.eclipse.xtend</groupId>
            <artifactId>org.eclipse.xtend.lib</artifactId>
            <version>${xtext.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.runtime</artifactId>
            <version>${org.eclipse.core.runtime.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.xtend</groupId>
            <artifactId>org.eclipse.xtend.core</artifactId>
            <version>${xtext.version}</version>
            <optional>true</optional>
        </dependency>

        <!-- Test -->

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj-core.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>${jaxb-runtime.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.fuin</groupId>
            <artifactId>units4j</artifactId>
            <version>${units4j.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.openpojo</groupId>
            <artifactId>openpojo</artifactId>
            <version>${openpojo.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback-classic.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.fuin.xsample</groupId>
            <artifactId>org.fuin.xsample.dsl</artifactId>
            <version>${org.fuin.xsample.dsl.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>@{argLine} -Duser.language=en -Duser.region=US -Djavax.xml.accessExternalSchema=all</argLine>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jdeps-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>

        </plugins>

    </build>

</project>
